
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Jul 01 19:19:00 CEST 2018
//----------------------------------------------------

package sinjl;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int RBRACK = 27;
  public static final int LT = 11;
  public static final int SEMICOLON = 28;
  public static final int ELSE = 4;
  public static final int BOOL_LITERAL = 31;
  public static final int PLUS = 18;
  public static final int NOTEQ = 15;
  public static final int RBRACE = 25;
  public static final int RPAREN = 23;
  public static final int INT = 5;
  public static final int DECVAR = 8;
  public static final int WHILE = 7;
  public static final int LBRACK = 26;
  public static final int NOT = 12;
  public static final int IDENTIFIER = 29;
  public static final int OROR = 17;
  public static final int IF = 6;
  public static final int LBRACE = 24;
  public static final int LPAREN = 22;
  public static final int INT_LITERAL = 30;
  public static final int LTEQ = 14;
  public static final int MULT = 20;
  public static final int EOF = 0;
  public static final int ANDAND = 16;
  public static final int MAIN = 9;
  public static final int DIV = 21;
  public static final int MINUS = 19;
  public static final int CONST = 3;
  public static final int error = 1;
  public static final int EQ = 10;
  public static final int BOOL = 2;
  public static final int EQEQ = 13;
}

